### ISSUE TITLE
Make all failing in html directory

### ISSUE THREAD

**Issue by ny2292000** [awsteiner/o2scl#11]
The computer is ubuntu 18.40
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
with a GPU

These are the steps I followed:
download from https://github.com/awsteiner/o2scl
cd o2scl-master
./autgen.sh
make

The recursive make fails at html folder.
[o2scl_Installation.txt](https://github.com/awsteiner/o2scl/files/4056753/o2scl_Installation.txt)

Please advise.

**Comment by awsteiner** [comment]
You need to either build the documentation or make blank documentation files before running make. This is documented at https://neutronstars.utk.edu/code/o2scl/html/install_section.html under the section called "Compiling on Linux": "Then, you will either need to generate the documentation from doxygen using make o2scl-doc or use make blank-doc to create blank documentation. Then you can proceed using make and make install."

**Comment by ny2292000** [comment]
Thank you a million.
