### ISSUE TITLE
Use of o2scl on a hyperspherical shell neutron star

### ISSUE THREAD

**Issue by ny2292000** [awsteiner/o2scl#12]
I created a theory where the Universe is a  Lightspeed Expanding Hyperspherical Hypersurface. At time zero the Universe had a 4D radius of 121.4 light-seconds.  This is known because my theory can predict the maximum density in a Black Hole.
As the Black Hole expands, it make a phase transition into a Neutron Star. Because of the topology, Gravitation is irrelevant.
The energy from the Big Bang comes from the neutron decay when the density reaches 300 MeV/fm**3.  That happens when the 4D radius is 804.9 light-seconds.

I need to calculate the value of x (fraction of proton) as the density decreases due to the inertial expansion.

The fraction of protons will define the available energy available to excite hyperspherical acoustic oscillations. The fast decay of the speed of sound inside the Neutronium works as a short-pass filter because longer wavelengths take longer to be recur.  So, there is no adjustable parameters in my theory and my expectation is that I will get the observed CMB observed modulation.

I would like your advice on how to use o2scl to model the Big Bang process.   My initial idea was just to make pressure equal to zero to get the value of x as the density decays in a known fashion.  
Knowing the available energy at any given time, one would create a feedback loop to reproduce the fact that energy being released in a region makes that region less dense and that increases the local neutron decay rate.

Ideally, I would like to make the full simulation.  That might be as easy as a single short python script.

Please advise.

**Comment by awsteiner** [comment]
This would require quite a bit of custom code and is not something that o2scl can be easily adapted to do.

**Comment by ny2292000** [comment]
Would you consider advise me or collaborate in an article?

**Comment by ny2292000** [comment]
By the way, on equation (3) in this article
https://arxiv.org/pdf/1303.4662.pdf
Am I wrong to consider that if I make Pressure equal to zero, and use the standard values for alphaL and nL, I end up with an equation for x as a function of density n-bar?

Does that match my problem?

**Comment by awsteiner** [comment]
P=0 only at zero density, and in isospin-symmetric matter at the nuclear saturation density. Inside a neutron star, the pressure must always be positive (and must increase with decreasing radius).

**Comment by ny2292000** [comment]
Dear Andrew,

I made progress.  Please correct me if I am wrong.
From the paper, I understand that the energy is potential energy.  I am modeling the process where the whole Neutron Star evaporates under Zero Gravity.
My suspicion is that I have to add the energy released by neutron decay as kinetic energy transferred to electrons.
So, I am changing those equations to reflect the extra thermal energy:

to


Would that be correct?  Of course, if this energy is the potential energy, I can just write another equation for the Kinetic energy and relate that to Temperature.
Later, I will related this energy to temperature by
I am not clear on the meaning of this energy.  Is this the energy per nucleon at density y.I supposed that to be the case, that is how I got the y**2 on the pressure.
Thanks you in advance for your attention and guidance.
Thanks,
Marco

    On Tuesday, January 21, 2020, 03:51:28 PM EST, Andrew W. Steiner <notifications@github.com> wrote:  
 
 
P=0 only at zero density, and in isospin-symmetric matter at the nuclear saturation density. Inside a neutron star, the pressure must always be positive (and must increase with decreasing radius).
