### ISSUE TITLE
hdf5.h no such file or directory

### ISSUE THREAD

**Issue by ishfaq333** [awsteiner/o2scl#14]
I successfully installed the o2scl program in my Ubuntu 18.04
No when I was trying to compile an example, I got this error:

![Screenshot from 2020-01-30 11-12-22](https://user-images.githubusercontent.com/60423184/73426703-07ca3a00-435b-11ea-9c68-c43a06306d02.png)

**Comment by awsteiner** [comment]
The instructions for compiling the examples are at 

https://neutronstars.utk.edu/code/o2scl/html/examples_section.html

If that doesn't work, you may need to create your own makefile which includes the proper compiler flags to find the relevant include files and libraries and then sets LD_LIBRARY_PATH appropriately.

**Comment by ishfaq333** [comment]
How to compile programs in src folder.

**Comment by ishfaq333** [comment]
The output files produced by the programs in the example folder do not contain any set of data.
All they have is the single values.
 How can I obtain complete data files so that I can plot the data results

**Comment by ishfaq333** [comment]
ishfaq@ishfaq:~/o2scl-0.924/src/eos$ g++ eos_had_rmf.cpp 
In file included from /usr/local/include/o2scl/part.h:38:0,
                 from /usr/local/include/o2scl/eos_had_rmf.h:35,
                 from eos_had_rmf.cpp:27:
/usr/local/include/o2scl/hdf_file.h:37:10: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
          ^~~~~~~~
compilation terminated.
ishfaq@ishfaq:~/o2scl-0.924/src/eos$ locate hdf5.h
/home/ishfaq/o2scl-0.924/src/hdf/hdf5.h
/snap/o2scl/3038/usr/include/hdf5/serial/hdf5.h
/usr/include/hdf5/serial/hdf5.h
/usr/local/include/o2scl/hdf5.h
/usr/local/include/o2scl/hdf5/serial/hdf5.h
/usr/local/serial/hdf5.h
ishfaq@ishfaq:~/o2scl-0.924/src/eos$ export CPATH="/usr/local/serial/"
ishfaq@ishfaq:~/o2scl-0.924/src/eos$ locate hdf5.h
/home/ishfaq/o2scl-0.924/src/hdf/hdf5.h
/snap/o2scl/3038/usr/include/hdf5/serial/hdf5.h
/usr/include/hdf5/serial/hdf5.h
/usr/local/include/o2scl/hdf5.h
/usr/local/include/o2scl/hdf5/serial/hdf5.h
/usr/local/serial/hdf5.h
^[[Aishfaq@ishfaq:~/o2scl-0.924/src/eos$ g++ eos_had_rmf.cpp 
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/ccfSSOrU.o: In function `o2scl::eos_had_rmf::saturation()':
eos_had_rmf.cpp:(.text+0x8408): undefined reference to `o2scl::eos_had_base::fcomp(double, double)'
eos_had_rmf.cpp:(.text+0x8445): undefined reference to `o2scl::eos_had_base::fkprime(double, double)'
eos_had_rmf.cpp:(.text+0x8482): undefined reference to `o2scl::eos_had_base::fesym(double, double)'
/tmp/ccfSSOrU.o: In function `o2scl::eos_had_rmf::calc_temp_e_solve_fun(unsigned long, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > const&, boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > >&)':

PLEASE HELP!!!!!!!!!

**Comment by awsteiner** [comment]
As I mentioned in my comment above, you will either need to follow the instructions to compille the examples, or you will need to create your own makefile. O2scl is principally a library, not a program in and of itself. You may want to try creating your program which uses the Gnu Scientific Library (GSL) as an exercise, and then, once that is working, try using O2scl. GSL is easier because it is C-only and so the API is more intuitive. Please do not create more issues on github on this same topic.
