### ISSUE TITLE
eos_quark_cfl6: Test fails due to tolerance issues on 64-bit (but not on 32-bit)

### ISSUE THREAD

**Issue by badshah400** [awsteiner/o2scl#18]
When building o2scl version 0.926 on openSUSE Tumbleweed, one of the tests fails on `x86_64` (but not on 32 bit arch) due to tolerance issues:

```
[  606s] Some tests failed in file: eos_quark_cfl6.scr
[  606s] FAIL: relative -2.287555e-03 vs. -2.287281e-03 : 1.193674e-04 > 1.000000e-04
[  606s]  qqu
[  606s] 8261 tests performed.
[  606s] At least one test failed.
[  606s] Last failed test: -2.287555e-03 vs. -2.287281e-03 : 1.193674e-04 > 1.000000e-04
[  606s]  qqu
[  606s] One or more O2scl tests failed.
```

Some details about the system configuration and libraries used when building as follows:
 * Armadillo 10.8.2
 * Arpack-NG 3.8.0
 * Boost 1.78
 * Eigen 3.4.0
 * GCC 11
 * HDF5 1.10.8 (recently updated from version 1.10.7, and it looks like the problem started right after but I am not too sure about this)
 * SuperLU 5.3.0

Thanks again for the great library.

**Comment by awsteiner** [comment]
Fixed today on commit 3f8a0dbb728bb22a8cd . Thank you for the report!
