### ISSUE TITLE
about dependences and tests

### ISSUE THREAD

**Issue by cypro666** [awsteiner/o2scl#3]
Good stuff! More happy to using this library than gsl in c-style , but three small questions:
1 ../../include/o2scl/hdf_file.h:31:18: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
In fact , I never use hdf5, so the add some condition compilings into conf?

2 No unit test?

3 chmod +x autogen.sh  :)

**Comment by awsteiner** [comment]
./configure --disable-hdf --disable-eoslib --disable-partlib 
should work to disable HDF5 I/O and
make check 
should also work (with or without HDF5 support). Let me know if they don't. 
I'll fix the permissions on autogen.sh in the next commit to master.

**Comment by cypro666** [comment]
Thanks~
