### ISSUE TITLE
doxyfile missing from release tarball leading to xml_ts test failure

### ISSUE THREAD

**Issue by badshah400** [awsteiner/o2scl#38]
The doxygen [config file](../tree/main/doc/o2scl/doxyfile) is missing from the [release tarball](../releases/download/v0.929/o2scl-0.929.tar.gz)  — but is included in GitHub's automatically generated tarballs — leading to a failure in the xml_ts test due to the required xml file not being generated (I think). Manually including the `doxyfile` as an additional source for the package build and copying it to the appropriate dir leads to the test succeeding.

**Comment by awsteiner** [comment]
I should have marked pugixml support as dev-only, as I don't intend to support this for end users. As long as you disable that you should be good. See https://hub.docker.com/layers/awsteiner/o2scl/v0.929_ot_plus/images/sha256-0676ca2e129102f87890a9d4812ec3514e25588d09d43df4f84b2044d60be4b7?context=repo . 
I've fixed the documentation to make this more explicit in future versions.
